# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0003_auto_20180109_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('kernel', models.CharField(blank=True, max_length=100)),
                ('cpu_number', models.IntegerField(blank=True, null=True)),
                ('vcpu_number', models.IntegerField(blank=True, null=True)),
                ('cpu_core', models.IntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('disk', models.CharField(blank=True, max_length=100)),
                ('swap', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='服务器类型')),
                ('selinux', models.CharField(blank=True, max_length=10)),
                ('distribution', models.CharField(blank=True, max_length=25)),
                ('distribution_version', models.CharField(blank=True, max_length=25)),
                ('manufacturer', models.CharField(blank=True, max_length=25)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=10)),
                ('console_ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='console_ip', to='components.Ipv4Address')),
                ('ipv4', models.ManyToManyField(blank=True, to='components.Ipv4Address')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Machine_status')),
                ('tag', models.ManyToManyField(blank=True, to='components.Machine_tag')),
            ],
            options={
                'verbose_name': '服务器信息',
            },
        ),
    ]
